### ISSUE TITLE
Not sure if keymap works to display menu of targets or devices

### ISSUE THREAD

**Issue by interstateone** [mjbeauregard/appcode-scheme-selector#1]
Previously when I used the built-in target selector I could set up a keymap to open the dropdown and change it without having to use a mouse. I tried doing the same for the target and device dropdowns in this plugin but couldn't seem to make it work. Looking at the code and docs, as someone who hasn't had any exposure to how this works, it seems like there isn't anything special to do in order for keymaps to work. Does this work for you?

**Comment by mjbeauregard** [comment]
Do you remember what action you had your key bound to?

**Comment by interstateone** [comment]
Command+Shift+Control+T and Command+Shift+Control+D are Select Target and Select Device respectively.

**Comment by mjbeauregard** [comment]
I added a couple actions called "Select Device..." and "Select Target..." that will popup the appropriate combo box. Let me know how this works out for you.

**Comment by interstateone** [comment]
Hmm, it seems like AppCode is getting confused about something. The dropdown menus aren't visible anymore. Getting this when I try to add something to the toolbar. This was after the scheme selector plugin wasn't visible at all in that list and I restarted AppCode.

<img width="523" alt="screen shot 2015-08-31 at 9 36 04 am" src="https://cloud.githubusercontent.com/assets/594059/9582631/d51d31f0-4fc3-11e5-9af9-6a3634747dad.png">

**Comment by mjbeauregard** [comment]
I can't reproduce that problem, but it could be because I had uninstalled it at some point while I was testing my changes. Can you try uninstalling/reinstalling the plugin and let me know if that has any effect?

**Comment by interstateone** [comment]
Same result.
